#ifndef INCLUDE_RMON_REG_H_
#define INCLUDE_RMON_REG_H_

#define RMON_REG_BID 0x0
#define RMON_REG_REVMAJ 0x1
#define RMON_REG_REVMIN 0x2
#define RMON_REG_REVRCS 0x3
#define RMON_REG_CRSHCTL 0x283
#define RMON_REG_CRSHSRC 0x404

#define RMON_REG_AQ       0x240
#define RMON_REG_FANSENSE 0x300
#define RMON_REG_PG       0x288

#define RMON_REG_TIME 0x6

#define RMON_REG_IRQFLG 0x2C0
#define RMON_REG_IRQMSK 0x2C2


#endif
