#
# arch/m68knommu/boot/Makefile
#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#

# for cleaning
subdir-y			:= images
